name: Update with Copier

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sundays

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install copier and pre-commit
        run: pip install copier pre-commit

      - name: Run copier update
        run: copier update --trust --defaults

      - name: Run pre-commit
        run: pre-commit run --all-files
        continue-on-error: true

      - name: Check for changes
        id: changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update template with copier"
          title: "Template update via copier"
          body: "Automated template update using copier"
          branch: copier-update
